.TH MPGEN 1
.SH NAME
mpgen
.SH SYNOPSIS
.B mpgen
.I [-h]
.I [-o outfile]
.I [file...]
.br
.SH DESCRIPTION
.PP
The 'mpgen' tool takes as input a list of mpgen sources, and compiles them
into myrddin source files that implement the parser generators described
within those input files.

.PP
Mpgen will, by default, output files in the form BASENAME.pg to files
in the form BASENAME.myr.

.PP
Mbld knows about mpgen, and mpgen files will be compiled correctly when included in bld.proj.

.PP
The mpgen options are:

.TP
.B -h, -?
Print a summary of the available options.

.TP
.B -o outfile
Output into file `outfile` instead of 


.SH EXAMPLE
.EX
    mpgen input.pg
    mpgen -o output-file-name input.pg
.EE

.SH FILES
The source for mpgen is available from
.B git://git.eigenstate.org/git/ori/mpgen.git

.SH SEE ALSO
.IR mc(1)
.IR mpgen(1)
.IR ld(1)
.IR as(1)

.SH BUGS
.PP
SLR(1) grammars are the only ones currently accepted.
.PP
Only myrddin output is supported
.PP
Line numbers are not currently set up
.PP
Many planned features aren't yet implmented.
